version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    timezone: Europe/Oslo
  open-pull-requests-limit: 20
  ignore:
  - dependency-name: org.mockito:mockito-core
    versions:
    - 3.8.0
