AWSTemplateFormatVersion: '2010-09-09'
Description: Persisting NVA Customers.

Parameters:
  NvaCustomersTableName:
    Description: Name to use for table persisting NVA Customers.
    Type: String
    Default: nva_customers

Resources:
  NvaCustomersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref NvaCustomersTableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: identifier
          AttributeType: S
        - AttributeNam: feideOrganizationId
          AttributeTypr: S
      KeySchema:
        - AttributeName: identifier
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: byOrgNumber
          KeySchema:
            - AttributeName: feideOrganizationId
              KeyType: HASH
          Projection:
            NonKeyAttributes:
            ProjectionType: ALL

Outputs:
  NvaCustomersTableOutput:
    Description: NVA Customers table name.
    Value: !Ref NvaCustomersTable